unreleasedDir: unreleased
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: |
  {{- $lines := .Body | splitn "\n" 2 -}}
  - {{ $lines._0 | trimSuffix "." }} by @{{.Custom.Author}} in https://github.com/dagger/dagger/pull/{{.Custom.PR}}
  {{- with $lines._1 -}}
    {{- . | trim | indent 2 }}
  {{- end -}}
  block: true
    label: GitHub PR
  - key: Author
    label: GitHub Author
    type: string
    format: '### 🔥 Breaking Changes'
  - label: Changed
  - label: Deprecated
  - label: Removed
  - label: Fixed
  - label: Security
  - label: Dependencies
footerFormat: |-
  ### What to do next?
  - Read the [documentation](https://docs.dagger.io)
  - Follow us on [Twitter](https://twitter.com/dagger_io)
  beforeChangelogVersion: 1
  beforeKind: 1
  beforeFooterTemplate: 1
  beforeHeaderTemplate: 1
  endOfVersion: 1
envPrefix: CHANGIE_
